### ISSUE TITLE
Incorrect wheel for py3k

### ISSUE THREAD

**Issue by webknjaz** [bbangert/routes#31]
Hi @bbangert,
when I'm trying to install `Routes==2.0` with `pip` under `python 3` I get following error (from `pip.log`):
```py
Cleaning up...
  Removing temporary dir /home/wk/private/work/source/cherrypy/.tox/py33/build...
Routes is in an unsupported or invalid wheel
Exception information:
Traceback (most recent call last):
  File "/home/wk/private/work/source/cherrypy/.tox/py33/lib/python3.3/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/home/wk/private/work/source/cherrypy/.tox/py33/lib/python3.3/site-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/home/wk/private/work/source/cherrypy/.tox/py33/lib/python3.3/site-packages/pip/req.py", line 1435, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/home/wk/private/work/source/cherrypy/.tox/py33/lib/python3.3/site-packages/pip/req.py", line 669, in install
    pip.wheel.check_compatibility(version, self.name)
  File "/home/wk/private/work/source/cherrypy/.tox/py33/lib/python3.3/site-packages/pip/wheel.py", line 438, in check_compatibility
    "%s is in an unsupported or invalid wheel" % name
pip.exceptions.UnsupportedWheel: Routes is in an unsupported or invalid wheel
```

The snippet (from `site-packages/pip/wheel.py`) which generates the exception is 
```py
def check_compatibility(version, name):
    """
    Raises errors or warns if called with an incompatible Wheel-Version.

    Pip should refuse to install a Wheel-Version that's a major series
    ahead of what it's compatible with (e.g 2.0 > 1.1); and warn when
    installing a version only minor version ahead (e.g 1.2 > 1.1).

    version: a 2-tuple representing a Wheel-Version (Major, Minor)
    name: name of wheel or package to raise exception about

    :raises UnsupportedWheel: when an incompatible Wheel-Version is given
    """
    if not version:
        raise UnsupportedWheel(
            "%s is in an unsupported or invalid wheel" % name
        )
    if version[0] > VERSION_COMPATIBLE[0]:
        raise UnsupportedWheel(
            "%s's Wheel-Version (%s) is not compatible with this version "
            "of pip" % (name, '.'.join(map(str, version)))
        )
    elif version > VERSION_COMPATIBLE:
        logger.warn('Installing from a newer Wheel-Version (%s)'
                    % '.'.join(map(str, version)))
```

So I guess it should be repackaged.

P.S. Attempt to install it from git (`./.tox/py33/bin/pip install git+https://github.com/bbangert/routes.git`) succeeds. I faced this issue while running `tox` in `cherrypy` repo.

**Comment by bbangert** [comment]
Seems universal wheels are incompatible with 2to3. So I've removed the wheel from pypi entirely, the sdist should be fine.

**Comment by fungi** [comment]
Yep, you'd have to upload separate py2 and py3 wheels and only use 2to3 on the latter. The point of wheels is that they're static and nothing gets run on installation, so obviously any transformations you need to make to the source would have to happen before building a wheel.
