### ISSUE TITLE
routes.middleware not Python 2.x compatible (ImportError: No module named request)

### ISSUE THREAD

**Issue by fungi** [bbangert/routes#37]
New in routes 2.1...
```python
Python 2.7.6 (default, Mar 22 2014, 15:40:47) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import routes.middleware
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/routes/local/lib/python2.7/site-packages/routes/__init__.py", line 145, in <module>
    from routes.mapper import Mapper
  File "/scratch/routes/local/lib/python2.7/site-packages/routes/mapper.py", line 8, in <module>
    from routes.util import (
  File "/scratch/routes/local/lib/python2.7/site-packages/routes/util.py", line 10, in <module>
    import urllib.request, urllib.parse, urllib.error
ImportError: No module named request
```

It looks like util.py assumes a Py3K urllib rather than using urllib2.Requests here?

**Comment by LotharSee** [comment]
Same issue here while trying to import routes.Mapper with a Python 2.7.

```
Python 2.7.3 (default, Feb 27 2014, 19:58:35)
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from routes import Mapper
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vagrant/project/python/lib/python2.7/site-packages/routes/__init__.py", line 145, in <module>
    from routes.mapper import Mapper
  File "/home/vagrant/project/python/lib/python2.7/site-packages/routes/mapper.py", line 8, in <module>
    from routes.util import (
  File "/home/vagrant/project/python/lib/python2.7/site-packages/routes/util.py", line 10, in <module>
    import urllib.request, urllib.parse, urllib.error
ImportError: No module named request
```

**Comment by bbangert** [comment]
Sigh, you'd think one of the Travis tests would've caught this.

Ok, I'm genuinely confused how this is in there, since line 10 of routes/util.py is merely "import urllib".

**Comment by bbangert** [comment]
Ok, I think perhaps it was the universal wheel that was messed up. I've removed it entirely. Please remove Routes, and try installing it again and let me know if you get this error.

**Comment by LotharSee** [comment]
Now it works!
That was a really strange bug, thanks for fixing it.

**Comment by bbangert** [comment]
No prob, seems the universal wheel bit runs after 2to3 ran, so the binary upload was pegged to py3.

**Comment by fungi** [comment]
Yep, it gets past that error anyway. Now I'm finding that routes.middleware tries to use webob even though it's not declared as a dependency (and so not dragged into the venv by pip install routes). I'll open a separate issue for that I guess.
